export function createContext() {
  const dom = {
    viewport: document.getElementById("viewport"),
    statusEl: document.getElementById("status"),
    tilePaletteEl: document.getElementById("tile-palette"),
    sketchPaletteEl: document.getElementById("sketch-palette"),
    objectPaletteEl: document.getElementById("object-palette"),
    intentInput: document.getElementById("intent-input"),
    intentRun: document.getElementById("intent-run"),
    proposalSummary: document.getElementById("proposal-summary"),
    proposalList: document.getElementById("proposal-list"),
    proposalApply: document.getElementById("proposal-apply"),
    proposalReject: document.getElementById("proposal-reject"),
    brushSizeInput: document.getElementById("brush-size"),
    brushSizeLabel: document.getElementById("brush-size-label"),
    zoomInput: document.getElementById("zoom-level"),
    zoomLabel: document.getElementById("zoom-label"),
    minimapCanvas: document.getElementById("minimap"),
    undoBtn: document.getElementById("undo-btn"),
    redoBtn: document.getElementById("redo-btn"),
    exportBtn: document.getElementById("export-btn"),
    importBtn: document.getElementById("import-btn"),
    importInput: document.getElementById("import-input"),
    toolButtons: Array.from(document.querySelectorAll("[data-tool]")),
    modeSketchBtn: document.getElementById("mode-sketch"),
    modeTileBtn: document.getElementById("mode-tile"),
    sketchPaletteSection: document.getElementById("sketch-palette-section"),
    tilePaletteSection: document.getElementById("tile-palette-section"),
    objectPaletteSection: document.getElementById("object-palette-section"),
    workflowGenerateBtn: document.getElementById("workflow-generate-tiles"),
    workflowPrettifyBtn: document.getElementById("workflow-prettify-tiles"),
    workflowRefineBtn: document.getElementById("workflow-refine-map"),
    refineTargetWidth: document.getElementById("refine-target-width"),
    refineTargetHeight: document.getElementById("refine-target-height"),
    refineBaseLabel: document.getElementById("refine-base"),
    refineTileset: document.getElementById("refine-tileset"),
    refineDecor: document.getElementById("refine-decor"),
    refineSeed: document.getElementById("refine-seed"),
    noteText: document.getElementById("note-text"),
    noteWidth: document.getElementById("note-width"),
    noteHeight: document.getElementById("note-height"),
    notesList: document.getElementById("notes-list")
  };

  dom.minimapCtx = dom.minimapCanvas ? dom.minimapCanvas.getContext("2d") : null;

  return {
    dom,
    state: {
      mode: "sketch",
      tool: "paint",
      selectedTileId: null,
      selectedSketchId: null,
      selectedObjectType: null,
      selectionStart: null,
      selection: null,
      lassoCells: null,
      dragging: false,
      painting: false,
      paintingTileId: null,
      proposal: null,
      brushSize: 4,
      intentLocked: false,
      zoom: 1,
      panning: false,
      panStart: null,
      spaceDown: false,
      roadDrawing: false,
      roadDraftPoints: null,
      riverDrawing: false,
      riverDraftPoints: null,
      hoverInfo: ""
    },
    tilesById: {},
    tilesByName: {},
    objectsByType: {},
    sketchPaletteById: {},
    renderer: null,
    store: null,
    undoStack: null
  };
}
