export const els = {
  missionPill: document.getElementById("mission-pill"),
  validationPill: document.getElementById("validation-pill"),
  checkpointPill: document.getElementById("checkpoint-pill"),
  missionSummary: document.getElementById("mission-summary"),
  missionVibe: document.getElementById("mission-vibe"),
  missionSeed: document.getElementById("mission-seed"),
  missionVariants: document.getElementById("mission-variants"),
  missionBatch: document.getElementById("mission-batch"),
  forceLive: document.getElementById("force-live"),
  adventureMode: document.getElementById("adventure-mode"),
  adventureSelect: document.getElementById("adventure-select"),
  adventureId: document.getElementById("adventure-id"),
  adventureTitle: document.getElementById("adventure-title"),
  adventureHeroName: document.getElementById("adventure-hero-name"),
  adventureHeroMeta: document.getElementById("adventure-hero-meta"),
  adventureHeroSheet: document.getElementById("adventure-hero-sheet"),
  adventureActions: document.getElementById("adventure-actions"),
  adventureBg: document.getElementById("adventure-bg"),
  planButton: document.getElementById("plan-button"),
  generateButton: document.getElementById("generate-button"),
  validateButton: document.getElementById("validate-button"),
  saveButton: document.getElementById("save-button"),
  forceSaveButton: document.getElementById("force-save-button"),
  canvas: document.getElementById("mission-canvas"),
  minimap: document.getElementById("minimap"),
  objectiveList: document.getElementById("objective-list"),
  assetList: document.getElementById("asset-list"),
  generateAssets: document.getElementById("generate-assets"),
  dialogNodes: document.getElementById("dialog-nodes"),
  dialogEdges: document.getElementById("dialog-edges"),
  addNode: document.getElementById("add-node"),
  addChoice: document.getElementById("add-choice"),
  nodeId: document.getElementById("node-id"),
  nodeSpeaker: document.getElementById("node-speaker"),
  nodeText: document.getElementById("node-text"),
  nodeChoices: document.getElementById("node-choices"),
  updateNode: document.getElementById("update-node"),
  toggleGraph: document.getElementById("toggle-graph"),
  missionGraph: document.getElementById("mission-graph"),
  playtestButton: document.getElementById("playtest-button"),
  checkpointSelect: document.getElementById("checkpoint-select"),
  jumpCheckpoint: document.getElementById("jump-checkpoint"),
  openEditor: document.getElementById("open-editor"),
  renderAssets: document.getElementById("render-assets"),
  actionBar: document.getElementById("action-bar"),
  actionLabel: document.getElementById("action-label"),
  actionFill: document.getElementById("action-fill"),
  missionMeta: document.getElementById("mission-meta"),
  applyMissionMeta: document.getElementById("apply-mission-meta"),
  busyOverlay: document.getElementById("busy-overlay"),
  busyLabel: document.getElementById("busy-label"),
  errorModal: document.getElementById("error-modal"),
  errorMessage: document.getElementById("error-message"),
  errorCopy: document.getElementById("error-copy"),
  errorClose: document.getElementById("error-close"),
};

export const ctx = els.canvas?.getContext("2d");
export const miniCtx = els.minimap?.getContext("2d");
export const MIN_TILE_SIZE = 12;
export const MAX_TILE_SIZE = 28;
